name: docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
     contents: read
     packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - '8.1.19'
          - '8.2.6'
        variant:
          - 'zts'
          - 'nts'
        os:
          - 'buster'
          - 'bullseye'
        include:
          - variant: zts
            suffix: '-zts'
          - variant: nts
            suffix: ''
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ github.token }}'

      - run: sudo gem install mustache
      - run: make "${{ matrix.version }}${{ matrix.suffix }}-${{ matrix.os }}" BUILDX=true PUSH=true
