name: docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
     contents: read
     packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - '8.1.26'
          - '8.2.13'
          - '8.3.0'
        variant:
          - 'zts'
          - 'nts'
        os:
          - 'bookworm'
        include:
          - variant: zts
            suffix: '-zts'
          - variant: nts
            suffix: ''
    env:
      TAG: ${{ matrix.version }}${{ matrix.suffix }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ github.token }}'

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          context: .
          build-args: TAG=${{ env.TAG }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/s6n-labs/distroless-php:${{ env.TAG }}
